### PR TITLE
Home.java

### PR DESCRIPTION
**Pull request by rshbhdv**
hey @MorrisB--  I have tried to make this home page.I am a beginner so there will be many mistakes so please review these files and share your thoughts regarding these files.

### CODE REVIEW

**Comment by MorrisB--** [comment]
#22

**Comment by rshbhdv** [comment]
Hey @MorrisB-- I have done the changes as asked by you.

**Comment by MorrisB--** [comment]
Hey @rshbhdv , one more thing. We should probably update STRUCTURE.md and add details about the new Table.java class. I can do this if you like but since you created the class it may sound better in your words.

**Comment by rshbhdv** [comment]
Yeah its okay I will update the STRUCTRE.md.

**Pull request merged**
